### ISSUE TITLE
Model with id missing primaryKey

### ISSUE THREAD

**Issue by GeorgBraun** [kingsquare/swagger-sequelize#3]
Thanks a lot for providing swagger-sequelize!

I started using it last week and encountered the following issue:

If we define a Model with an id-property, we get an error like "Error: A column called 'id' was added to the attributes of 'Documents' but not marked with 'primaryKey: true'"

Example:

Model definition in `swagger.json`:

```JSON
"definitions": {
    "Document": {
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32",
                "description": "Unique Identifier representing a document"
            },
            "title": {
                "type": "string",
                "description": "Title of the document"
            },
            "author": {
                "type": "string",
                "description": "Author of the document"
            },
            "content": {
                "type": "string",
                "description": "Content of the document"
            }
        },
        "required": [
            "id",
            "title",
            "author",
            "content"
        ]
    }
}
```

Just for reference, the same model definition in `swagger.yaml`

```YAML
definitions:
  # Model definition
  Document:
    properties:
      id:
        type: integer
        format: int32
        description: Unique Identifier representing a document
      title:
        type: string
        description: Title of the document
      author:
        type: string
        description: Author of the document
      content:
        type: string
        description: Content of the document
    required:
      - id
      - title
      - author
      - content
```

After some debugging, I found that the error is produced within Sequelize, in file `node_modules/sequelize/lib/model.js`:

This file seems to scan the `rawAttributes` for `'primaryKey'` and `'id'`. If it finds an `'id'` without any `'primaryKey'`, it throws the exception `Error: A column called 'id' was added to the attributes of 'Documents' but not marked with 'primaryKey: true'`.

I am not sure if I am on the right track (I am new to **swagger-sequelize**), but I would see two possible solutions:

**Solution 1: Auto-promote an id with primaryKey and autoIncrement**

Idea: All Attributes with name `id` and with data type `integer` are promoted with primaryKey and autoIncrement.

* Pro: No changes in swagger api file required.
* Con: Potentially too agressive.

Implementation:

In swagger-sequelize-file `index.js`, extend `function generate (schema)` from 

```JavaScript
function generate (schema) {
	//poor mans deep-clone
	var result = JSON.parse(JSON.stringify(schema.properties));

	Object.keys(result).forEach((propertyName) => {
		var propertySchema = result[propertyName];
		propertySchema.type = getSequalizeType(propertySchema);
		if (propertySchema.default) {
			propertySchema.defaultValue = propertySchema.default;
		}
	});

	return result;
}
```

to

```JavaScript
function generate (schema) {
	//poor mans deep-clone
	var result = JSON.parse(JSON.stringify(schema.properties));

	Object.keys(result).forEach((propertyName) => {
		var propertySchema = result[propertyName];
		// BEGIN: Promote id-Integer-Attribute to primaryKey with autoIncrement
		if(propertyName.toLowerCase()=="id" && propertySchema.type==='integer') {
			propertySchema.primaryKey = true;
			propertySchema.autoIncrement = true;
		}
		// END: Promote id-Integer-Attribute to primaryKey with autoIncrement

		propertySchema.type = getSequalizeType(propertySchema);
		if (propertySchema.default) {
			propertySchema.defaultValue = propertySchema.default;
		}
	});

	return result;
}
```

**Solution 2: Use additional attribute "x-primary-key" to promote to primaryKey and autoIncrement**

Idea: If an attribute has an additional property "x-primary-key", it will be promoted with primaryKey and autoIncrement.

* Pro: Only done when desired by the api-spec-writer
* Con: Needs modification in swagger api file.

Implementation:

In swagger-sequelize-file `index.js`, extend `function generate (schema)` from 

```JavaScript
function generate (schema) {
	//poor mans deep-clone
	var result = JSON.parse(JSON.stringify(schema.properties));

	Object.keys(result).forEach((propertyName) => {
		var propertySchema = result[propertyName];
		propertySchema.type = getSequalizeType(propertySchema);
		if (propertySchema.default) {
			propertySchema.defaultValue = propertySchema.default;
		}
	});

	return result;
}
```

to

```JavaScript
function generate (schema) {
	//poor mans deep-clone
	var result = JSON.parse(JSON.stringify(schema.properties));

	Object.keys(result).forEach((propertyName) => {
		var propertySchema = result[propertyName];
		// BEGIN: Promote Attribute to primaryKey with autoIncrement
		if(propertySchema["x-primary-key"]==true) {
			propertySchema.primaryKey = true;
			propertySchema.autoIncrement = true;
		}
		// END: Promote Attribute to primaryKey with autoIncrement

		propertySchema.type = getSequalizeType(propertySchema);
		if (propertySchema.default) {
			propertySchema.defaultValue = propertySchema.default;
		}
	});

	return result;
}
```

To make this work, we need to add `"x-primary-key": true` in the model definition in `swagger.json`:

```JSON
"definitions": {
    "Document": {
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32",
                "description": "Unique Identifier representing a document",
                "x-primary-key": true
            },
```

And in `swagger.yaml`, it would be:

```YAML
definitions:
  # Model definition
  Document:
    properties:
      id:
        type: integer
        format: int32
        description: Unique Identifier representing a document
        x-primary-key: true
```

Maybe, there are some rules (unknown to me) how to deal with IDs. If so, I would be glad if you could point me to some reading material. If not, maybe the above proposals would come handy?

By the way, my current personal favorite is solution 2 (with `x-primary-key`)

Many thanks and best regards,
 Georg
